Functions task completed
julia-gorbatenko/aqa-advanced-1 pull request #6
Opened 2023-09-12 18:10 UTC by julia-gorbatenko

Functions task completed

2023-09-12 21:03 UTC, sttaran requested changes

2023-09-12 21:03 UTC, sttaran commented on functions/task2.js
> +const checkIfAdult=(age) => {
it's preferable to use precise arrow function with small expressions. But your code is correct. Just advice
```js
const checkIfAdult=(age) => age >= 18;
```

2023-09-12 21:03 UTC, sttaran commented on functions/task3.js
Фунція повинна викликатися, доки num не стане менше або рівне 0. 

That means function should not be called when num is 0

2023-09-15 15:43 UTC, julia-gorbatenko commented on functions/task1.js
> +    return square = width * height
Хотіла скоротити, але не додивилась(

2023-09-15 15:43 UTC, julia-gorbatenko commented on functions/task2.js
> +const checkIfAdult=(age) => {
Дякую за рекомендацію)

2023-09-15 15:43 UTC, julia-gorbatenko commented on functions/task3.js
Твоя правда, трохи не так трактувала умову

2023-09-17 18:32 UTC, merged